version: '3.8'

services:
  emsa-app:
    image: emsa-app
    build:
      context: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 8001
    ports:
      - "8001:8001"
    volumes:
      - ./pgadmin4-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pgadmin4-data:
